# Use root/example as user/password credentials
# Mongo should be 3.2.14
version: "3.1"

services:
  mongo:
    image: mongo:3.4.23
    restart: always
    networks:
      bigdata:
        ipv4_address: 192.168.1.2
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    networks:
      bigdata:
        ipv4_address: 192.168.1.3
    ports:
      - 8082:8081

  redis:
    image: "redis:latest"
    restart: always
    networks:
      bigdata:
        ipv4_address: 192.168.1.4
    ports:
      - 6379:6379

  redis-commander:
    build:
      context: ./redis-commander
      dockerfile: redis-commander-dockerfile
    image: redis-commander
    restart: always
    networks:
      bigdata:
        ipv4_address: 192.168.1.5
    ports:
      - 8081:8081

networks:
  bigdata:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
